spring:
  profiles:
    active: dev
  application:
    name: pairs-user-biz-acl
  http:
    encoding:
      charset: UTF-8
server:
  port: 11001
  contextPath: /v1
  display-name: pairs-user-biz-acl

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://rm-uf61501896t6034l1o.mysql.rds.aliyuncs.com:3306/canary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: JIAhao123
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
logback:
  behaviour:
    mongo: dev-behaviour-helper-mongo
    elasticsearch: dev-behaviour-helper-es
  log:
    elasticsearch: dev-log-helper-es

